### ISSUE TITLE
Crash when starting a new game

### ISSUE THREAD

**Issue by adamskt** [IntelliTect/Hackathon2022Keboom#41]
Stack trace from console:

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: ExpectedStartOfValueNotFound, < Path: $ | LineNumber: 1 | BytePositionInLine: 0.
System.Text.Json.JsonException: ExpectedStartOfValueNotFound, < Path: $ | LineNumber: 1 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: ExpectedStartOfValueNotFound, < LineNumber: 1 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& , ExceptionResource , Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte )
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte )
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1[[Keboom.Shared.GameState, Keboom.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   Exception_EndOfInnerExceptionStack
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException )
   at System.Text.Json.Serialization.JsonConverter`1[[Keboom.Shared.GameState, Keboom.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadCore[GameState](Utf8JsonReader& , JsonTypeInfo , ReadStack& )
   at System.Text.Json.JsonSerializer.ContinueDeserialize[GameState](ReadBufferState& , JsonReaderState& , ReadStack& , JsonTypeInfo )
   at System.Text.Json.JsonSerializer.<ReadFromStreamAsync>d__76`1[[Keboom.Shared.GameState, Keboom.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__5`1[[Keboom.Shared.GameState, Keboom.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Keboom.Client.ViewModels.GameBoardViewModel.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

**Comment by Keboo** [comment]
Appears fix with latest code.
